name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Puedes ajustar la versión de Node.js aquí

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # Cambia esto al comando de construcción real de tu proyecto

      - name: Deploy to Netlify
        run: npm run deploy-netlify # Cambia esto al comando para desplegar (si es necesario)

